include make.env/project.env
include make.env/docker.env
include make.env/database.env

include make.env/app.env
include make.env/jobs/ingestion_job.env
include make.env/jobs/simulation_job.env
include make.env/${DEV_DB_TYPE}/database.env
include make.env/${DEV_DB_TYPE}/secret.env

include make.env/elastic/stack.env
include make.env/elastic/search.env
include make.env/elastic/kibana.env
include make.env/elastic/apm.env
include make.env/elastic/secret.env

include make.env/cipher.env

export
