apiVersion: v1
kind: ConfigMap
metadata:
  name: garner-apm-configmap
data:
  ELASTIC_APM_SERVICE_NAME: data-xx-log-collector
  ELASTIC_APM_SERVER_URL: https://apm:8200
  ELASTIC_APM_SERVER_CA_CERT_FILE: /usr/local/share/ca-certificates/ca/ca.crt
  ELASTIC_APM_ENABLED: "true"
  ELASTIC_APM_POOL_SIZE: "7"

