apiVersion: v1
kind: ConfigMap
metadata:
  name: garner-service-configmap
data:
  APP_ENV: development
  # APP_ENV: test
  # APP_ENV: production

  # optional, will use db_host with db_name if opt out
  SERVICE_NAME: apm
  SLEEP_INTERVAL: '20'

