# xpack.encryptedSavedObjects.encryptionKey: "thirty-two-or-more-random-characters"
server.host: "0.0.0.0"
telemetry.enabled: "true"
xpack.fleet.packages:
  - name: elastic_agent
    version: latest
  - name: apm
    version: latest
  - name: fleet_server
    version: latest
xpack.fleet.agentPolicies:
  - name: Fleet-Server-Policy
    id: fleet-server-policy
    namespace: default
    package_policies:
      - name: fleet_server-1
        package:
          name: fleet_server
      - name: apm-1
        package:
          name: apm
        inputs:
          - type: apm
            keep_enabled: true
            vars:
              - name: host
                value: 0.0.0.0:8200
                frozen: false
              - name: url
                value: "${ELASTIC_APM_SERVER_URL}"
                frozen: false
              - name: enable_rum
                value: false
                frozen: false
              - name: read_timeout
                value: 1m
                frozen: false
              - name: shutdown_timeout
                value: 2m
                frozen: false
              - name: write_timeout
                value: 1m
                frozen: false
              - name: rum_allow_headers
                value:
                  - x-custom-header
                frozen: false
              - name: api_key_enabled
                value: true
              - name: secret_token
                value: "${ELASTIC_APM_SECRET_TOKEN}"
                frozen: false
              - name: tls_enabled
                value: "${APM_TLS}"
                frozen: false
              - name: tls_certificate
                value: "/certs/${APM_SERVICE}/${APM_SERVICE}.crt"
                frozen: false
              - name: tls_key
                value: "/certs/${APM_SERVICE}/${APM_SERVICE}.key"
                frozen: false
              - name: anonymous_allow_agent
                value:
                  - "ruby"
