version: "3.6"

services:
  # For development only
  app:
    depends_on:
      app.db:
        condition: service_healthy
      apm:
        condition: service_healthy
    image: ${DEV_IMAGE}
    env_file:
      - env/cipher.env
      - env/app.env
      - env/database.env
      - env/secret.env
      - env/apm.env
      - env/jobs/ingestion_job.env
      - env/jobs/simulation_job.env
    working_dir: ${APP_HOME}
    volumes:
      - ../../:${APP_HOME}
      - ../../vendor/bundle:/usr/local/bundle:z
      - ./env/jobs:${ENV_HOME}/jobs
      - ./.data/certs:${DEV_APM_SERVER_CA_CERT}
      - ../../../garnet:/gems/garnet
      - ../build/src:${SCHEMATIC_HOME}
    entrypoint: /bin/sh
    stdin_open: true
    tty: true
