apiVersion: v1
kind: Configmap
metadata:
  name: db-config
  namespace: garner
data:
  SERVICE_NAME: data_demo-dataops_garner
  DB_NAME: dataops_garner
  DATABASE_URL: tinytds://app.db/dataops_garner?textsize=1024000&timeout=500
  ENABLE_SQL_LOG: "false"
  USE_NAMED_SCHEMA: "false"
  DB_USER: user1

  APM_SERVER_URL: http://apm:8200
