apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: garner
type: Opaque
data:
  APM_SERVER_URL: http://apm:8200
  APM_SECRET_TOKEN: MWZmYzE3NjZiNDdkNDE0NmViOTcxYTgwMTBjMjJlNzM=

  DB__APP_DB1__DB_USER: dXNlcjE= #Base64 encoded 'user1'
  DB__APP_DB1__DB_PASSWORD: CGFzc3dvcmQx # Base64 encoded 'password1'
  DB__APP_DB2__DB_USER: dXNlcjI=
  DB__APP_DB2__DB_PASSWORD: cGFzc3dvcmQy
  # DB__APP_DB3__DB_USER: dXNlcjM=
  # DB__APP_DB3__DB_PASSWORD: cGfzc3dvcmQz

