apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: garner
type: Opaque
data:
  APM_SECRET_TOKEN: MWZmYzE3NjZiNDdkNDE0NmViOTcxYTgwMTBjMjJlNzM=

  DB_PASSWORD_ENCRYPTED: CGFzc3dvcmQx # Base64 encoded 'password1'

