BEGIN TRANSACTION;

DELETE FROM JOB_DETAILS_LOGS
WHERE JOB_LOG_ID IN (
    SELECT s.JOB_LOG_ID
    FROM JOB_STATUS_LOG l
    INNER JOIN JOB_DETAILS_LOGS s ON l.JOB_LOG_ID = s.JOB_LOG_ID
    WHERE l.LOG_COLLECTED = IS NOT NULL
);

DELETE FROM JOB_STATUS_LOGS
WHERE LOG_COLLECTED IS NOT NULL;

COMMIT TRANSACTION;
