BEGIN TRANSACTION;

DELETE FROM JOB_DETAILS_LOGS
WHERE ID IN (
    SELECT s.ID
    FROM JOB_STATUS_LOG l
    INNER JOIN JOB_DETAILS_LOGS s ON l.ID = s.JOB_LOG_ID
    WHERE l.COLLECTED = 1
);

DELETE FROM JOB_STATUS_LOGS
WHERE COLLECTED = 1;

COMMIT TRANSACTION;
