BEGIN TRANSACTION;

DELETE FROM JOB_STEP_LOGS
WHERE ID IN (
    SELECT s.ID
    FROM JOB_LOGS l
    INNER JOIN JOB_STEP_LOGS s ON l.ID = s.JOB_LOG_ID
    WHERE l.COLLECTED = 1
);

DELETE FROM JOB_LOGS
WHERE COLLECTED = 1;

COMMIT TRANSACTION;
