SELECT
  ETL_PROCEDURE,
  SUM(CASE WHEN LOG_COLLECTED IS NULL THEN 1 ELSE 0 END) AS Collected_0_Count,
  SUM(CASE WHEN LOG_COLLECTED IS NOT NULL THEN 1 ELSE 0 END) AS Collected_1_Count
FROM
  JOB_STATUSLOGS
GROUP BY
  ETL_PROCEDURE;

